# Generated by Django 5.2.6 on 2025-10-03 22:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5)])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(20)])),
                ('movie_title', models.CharField(help_text='The title of the movie you want to request', max_length=255)),
                ('movie_year', models.IntegerField(blank=True, help_text='Year the movie was released', null=True)),
                ('movie_director', models.CharField(blank=True, help_text='Director of the movie', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this petition is still accepting votes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_petitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movie Petition',
                'verbose_name_plural': 'Movie Petitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='petitions.petition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petition_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Petition Vote',
                'verbose_name_plural': 'Petition Votes',
                'ordering': ['-created_at'],
                'unique_together': {('petition', 'user')},
            },
        ),
    ]
