# Generated by Django 5.0 on 2025-09-18 19:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(10)])),
                ('answer', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_phrase', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Phrase',
                'verbose_name_plural': 'Security Phrases',
            },
        ),
    ]
